# Generated by Django 5.2.12 on 2026-05-27 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(verbose_name='Date et heure')),
                ('location', models.CharField(max_length=300, verbose_name='Lieu')),
                ('location_link', models.URLField(blank=True, null=True, verbose_name='Lien Google Maps/Zoom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image')),
                ('max_participants', models.IntegerField(default=0, verbose_name='Max participants (0 = illimité)')),
                ('status', models.CharField(choices=[('upcoming', '⏰ À venir'), ('ongoing', '🔴 En cours'), ('past', '✅ Passé'), ('cancelled', '❌ Annulé')], default='upcoming', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='⭐ À la une')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': '📅 Événements',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('attended', models.BooleanField(default=False, verbose_name='Présent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', verbose_name='Événement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': '👥 Participants',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
