# Generated by Django 5.2.12 on 2026-05-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Icône Bootstrap (ex: bi-mic)', max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('speaker', models.CharField(max_length=100, verbose_name='Prédicateur/Enseignant')),
                ('description', models.TextField(verbose_name='Description')),
                ('content_type', models.CharField(choices=[('audio', '🎵 Audio'), ('video', '🎥 Vidéo'), ('pdf', '📄 PDF'), ('text', '📝 Texte')], max_length=10, verbose_name='Type de contenu')),
                ('file', models.FileField(blank=True, null=True, upload_to='teachings/', verbose_name='Fichier')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien YouTube/Vimeo')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Lien externe')),
                ('duration', models.CharField(blank=True, help_text='ex: 34min', max_length=20, verbose_name='Durée')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, verbose_name='Vues')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachings', to='teachings.teachingcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Enseignement',
                'verbose_name_plural': 'Enseignements',
                'ordering': ['-created_at'],
            },
        ),
    ]
