# Generated by Django 5.2.12 on 2026-05-27 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('church', models.CharField(blank=True, max_length=100, verbose_name="Église d'origine")),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biographie')),
                ('member_type', models.CharField(choices=[('staff', '👑 Membre du Staff'), ('regular', "🙏 Jeune de l'église"), ('guest', '👤 Invité')], default='guest', max_length=20, verbose_name='Type de membre')),
                ('department', models.CharField(blank=True, choices=[('coordination', '🎯 Coordination'), ('evangelisation', '📢 Évangélisation'), ('louange', '🎵 Louange'), ('enseignement', '📖 Enseignement'), ('technique', '💻 Technique / Médias'), ('communication', '📱 Communication'), ('accueil', '🤝 Accueil'), ('priere', '🙏 Prière'), ('social', '❤️ Action sociale')], max_length=20, null=True, verbose_name='Département')),
                ('is_regular_member', models.BooleanField(default=False, verbose_name='Prie déjà dans notre église')),
                ('is_leader', models.BooleanField(default=False, verbose_name='Leader du groupe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
