# Generated by Django 5.2.12 on 2026-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('comité d’organisation', '🎯 Comité d’organisation'), ('secrétariat', '🧑\u200d🏫 Secrétariat'), ('finance', '💸 Finance'), ('presse', '🎥 Presse'), ('intercession', '🤲 Intercession'), ('lecture', '📖 Lecture'), ('son et musique\u2060', '🎵 Son et musique\u2060'), ('protocole', '👩\u200d💼 Protocole'), ('evangélisation et suivie', '📢 Évangélisation et suivie'), ('social', '❤️ Social'), ('logistique et propreté', '😎Logistique et propreté'), ('affaire extérieure', '👩\u200d💼 Affaire extérieure'), ('organisation de jeudi', '🙏 Organisation de jeudi'), ('l’encadrement de jeunes sœurs et conseils', '❤️ L’encadrement de jeunes sœurs et conseils')], max_length=50, null=True, verbose_name='Département'),
        ),
    ]
