# Generated by Django 5.2.12 on 2026-05-27 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('orange', 'Orange Money')], max_length=20, verbose_name='Moyen de paiement')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID Transaction')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Don anonyme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-created_at'],
            },
        ),
    ]
